name: QA Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - 1.0.0
  pull_request:
    branches:
      - master
      - develop
    # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  QAFlow:
    runs-on: ubuntu-latest

    steps:
    # Intenta restaurar el compilador desde la caché
      - name: Cache ARM GCC
        uses: actions/cache@v3
        with:
          path: ~/.gcc-arm-none-eabi
          key: arm-gcc-${{ runner.os }}
          restore-keys: |
            arm-gcc-
      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v2
        with:
          release: "13.3.Rel1" # <-- The compiler release to use

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen gcovr lcov cppcheck graphviz clang-format
          version: 1.0

      - name: Run style check
        uses: ./.github/actions/style

      - name: Run documentation check
        uses: ./.github/actions/document

      - name: Build project
        uses: ./.github/actions/build
